
<!--Escribir un documento XML con una DTD interna que represente la siguiente información ficticia:
PANEL DE VUELOS DE SALIDA DEL AEROPUERTO JFK – 20/12/2013
Código	Diario	Origen	Destino	Hora salida	Hora llegada	Estado
V22	     SI	  New York	Chicago	  9:30	        11:30	     R
V23	     NO   New York	Miami	  10:15     	11:15	      C

Consideraciones respecto a la DTD:
Hay que guardar el nombre del aeropuerto, los datos de cada vuelo agrupados y la fecha del panel, en ese orden.
En la DTD, sólo el código de un vuelo y su estado deben representarse mediante atributos.
Se tiene que indicar que el código ha de ser único y obligatorio para cada vuelo.
Los posibles estados de un vuelo son C (Cancelado), E (En hora), R (Retrasado). El valor por defecto debe ser E.
En la DTD debe indicarse que al menos tiene que aparecer un vuelo y, para cada uno de ellos, se tiene que guardar la información en el mismo orden en el que aparece en el panel.
Para indicar si un vuelo es diario, se debe utilizar un elemento vacío que, respecto a cada vuelo, podrá aparecer (en el caso de sí ser diario) o no aparecer (en el caso contrario).-->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE europuerto [
<!ELEMENT aeropuerto (nombre, vuelos, fecha)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT vuelos (vuelo+)>
        <!ELEMENT vuelo (diario?,origen,destino,salida,llegada)>
            <!ATTLIST vuelo codigo ID #REQUIRED>
            <!ATTLIST vuelo estado (C | E | R) "E">
            <!ELEMENT diario EMPTY>
            <!ELEMENT origen (#PCDATA)>
            <!ELEMENT destino (#PCDATA)>
            <!ELEMENT salida (#PCDATA)>
            <!ELEMENT llegada (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
]>

<aeropuerto>
    <nombre>JFK</nombre>
    <vuelos>
        <vuelo codigo="V22" estado="R">
            <diario/>
            <origen>New York</origen>
            <destino>Chicago</destino>
            <salida>9:30</salida>
            <llegada>11:30</llegada>
        </vuelo>
        <vuelo codigo="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <salida>10:15</salida>
            <llegada>11:15</llegada>
        </vuelo>
    </vuelos>
    <fecha>20/12/2013</fecha>
</aeropuerto>
