=== MariD3v/XML/XSD/alumno.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="edad" type="xs:integer"/>
              <xs:element name="nota" minOccurs="1" maxOccurs="3"/>
                <xs:complexType>
                <xs:simpleContent>
                <xs:extension base="xs:decimal">
                <xs:attribute name="eval" type="xs:integer"></xs:attribute>
                </xs:extension>
                </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="telefono" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="dni" type="xs:string" use="required"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MariD3v/XML/XSD/alumno.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/E:/Clase/Lenguaje%20de%20marcas/XML/XSD/alumno.xsd">
  <alumno dni="12312312A">
    <nombre>Mari</nombre>
    <edad>24</edad>
    <nota eval="1">10</nota>
    <nota eval="2">9</nota>
    <telefono prefijo="+34">567567567</telefono>
  </alumno>
  <alumno dni="12312312B">
    <nombre>MariChuli</nombre>
    <edad>24</edad>
    <nota eval="2">10</nota>
    <nota eval="1">9</nota>
  </alumno>
</alumnos>
