=== MariD3v/XML/XSD/heladeria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="heladería">
        <xs:complexType>
        <xs:sequence>
        <xs:element  name="helado" minOccurs="1" maxOccurs="unbounded">
            <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="chocolate">
                        <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="1000"/>
                        </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                     <xs:element name="fresa">
                        <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="1000"/>
                        </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:choice>
                <xs:choice>
                    <xs:element name="vainilla">
                        <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="1000"/>
                        </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                     <xs:element name="mango">
                        <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="1000"/>
                        </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:choice>
                <xs:element name="apto-para-celíacos" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="fecha-fabricación" type="xs:date"/>
            </xs:complexType>
        </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MariD3v/XML/XSD/heladeria.xml
<?xml version="1.0" encoding="UTF-8"?>
<heladería xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="heladeria.xsd">
  <helado fecha-fabricación="2015-01-30">
    <chocolate>250</chocolate>
    <mango>300</mango>
  </helado>
  <helado fecha-fabricación="2015-01-30">
    <fresa>500</fresa>
    <vainilla>200</vainilla>
    <apto-para-celíacos/>
  </helado>
</heladería>
